services:

  vectordb:
    image: pgvector/pgvector:pg16
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"

  ollama:
    image: ollama/ollama:0.17.4
    volumes:
      - ./.ollama:/root/.ollama
    ports:
      - "11434:11434"
