spring:
  ai:
    google:
      genai:
        api-key: "${GOOGLE_API_KEY}"
        project-id: "xxx"
        chat:
          options:
            model: "gemini-3-flash-preview"
            temperature: 0.7
        embedding:
          api-key: "${GOOGLE_API_KEY}"
          project-id: "xxx"
          text:
            options:
              model: "gemini-embedding-001"
              dimensions: 768
    vectorstore:
      pgvector:
        dimensions: 768
        initialize-schema: true
