spring:
  profiles:
    active: "bedrock"
  application:
    name: "banking-sentinel"
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "password"
    driver-class-name: org.postgresql.Driver

server:
  port: 8080

logging:
  level:
    org.springframework.ai.chat.client.advisor: INFO
